export const RESTAURANTS = [
  {
    id: "teenoi",
    name: "สุกี้ตี๋น้อย",
    type: "สุกี้ • บุฟเฟต์",
    category: "ชาบู",
    wait: 35,
    people: 18,
    price: 276,
    rating: 4.6,
    worth: 87,
    distance: 280,
    popular: true,
    img: "/assets/teenoi_mbk.jpg",
    ratings: {
      รสชาติ: 4.7,
      ราคา: 4.8,
      เวลารอ: 3.7,
      ปริมาณ: 4.8,
      ประสบการณ์: 4.4,
    },
  },
  {
    id: "kubkao",
    name: "กับข้าวกับปลา",
    type: "อาหารไทยร่วมสมัย",
    category: "อาหารไทย",
    wait: 15,
    people: 6,
    price: 420,
    rating: 4.7,
    worth: 91,
    distance: 190,
    popular: true,
    img: "/assets/kubkao_kubpla.jpeg",
    ratings: {
      รสชาติ: 4.8,
      ราคา: 4.1,
      เวลารอ: 4.5,
      ปริมาณ: 4.3,
      ประสบการณ์: 4.7,
    },
  },
  {
    id: "katsu",
    name: "คัตสึยะ",
    type: "ข้าวหน้าหมูทอดญี่ปุ่น",
    category: "ญี่ปุ่น",
    wait: 8,
    people: 3,
    price: 220,
    rating: 4.4,
    worth: 89,
    distance: 120,
    popular: false,
    img: "/assets/katsu.jpg",
    ratings: {
      รสชาติ: 4.4,
      ราคา: 4.6,
      เวลารอ: 4.8,
      ปริมาณ: 4.5,
      ประสบการณ์: 4.1,
    },
  },
  {
    id: "somtam",
    name: "ตำมั่ว สยาม",
    type: "อาหารอีสาน",
    category: "อาหารไทย",
    wait: 22,
    people: 9,
    price: 260,
    rating: 4.5,
    worth: 84,
    distance: 350,
    popular: true,
    img: "/assets/noodles-2.jpg",
    ratings: {
      รสชาติ: 4.7,
      ราคา: 4.2,
      เวลารอ: 4.0,
      ปริมาณ: 4.5,
      ประสบการณ์: 4.3,
    },
  },
  {
    id: "ramen",
    name: "ฮะจิบัง ราเมน",
    type: "ราเมนญี่ปุ่น",
    category: "ญี่ปุ่น",
    wait: 12,
    people: 4,
    price: 190,
    rating: 4.3,
    worth: 86,
    distance: 240,
    popular: false,
    img: "/assets/noodles.jpg",
    ratings: {
      รสชาติ: 4.3,
      ราคา: 4.6,
      เวลารอ: 4.6,
      ปริมาณ: 4.1,
      ประสบการณ์: 4.0,
    },
  },
  {
    id: "barbq",
    name: "บาร์บีคิวพลาซ่า",
    type: "ปิ้งย่าง",
    category: "ปิ้งย่าง",
    wait: 45,
    people: 23,
    price: 480,
    rating: 4.6,
    worth: 82,
    distance: 410,
    popular: true,
    img: "/assets/katsu.jpg",
    ratings: {
      รสชาติ: 4.7,
      ราคา: 3.9,
      เวลารอ: 3.3,
      ปริมาณ: 4.3,
      ประสบการณ์: 4.6,
    },
  },
];

export const RESTAURANT_CATEGORIES = [
  "ทั้งหมด",
  "อาหารไทย",
  "ญี่ปุ่น",
  "ชาบู",
  "ปิ้งย่าง",
];

export const PRIORITY_LABELS = {
  balanced: "พอดีทุกด้าน",
  fast: "กินให้ไว",
  value: "คุ้มงบที่สุด",
  taste: "เน้นรสชาติ",
};

export const DEFAULT_PREFERENCE = {
  time: 25,
  budget: 350,
  priority: "balanced",
};

export const MEAL_TIME_OPTIONS = [
  { value: 15, label: "15 นาที", hint: "รีบมาก" },
  { value: 25, label: "25 นาที", hint: "พอดี" },
  { value: 40, label: "40 นาที", hint: "รอได้" },
  { value: 60, label: "1 ชั่วโมง", hint: "ไม่รีบ" },
];

export const MEAL_BUDGET_OPTIONS = [
  { value: 200, label: "ไม่เกิน ฿200", hint: "ประหยัด" },
  { value: 350, label: "ไม่เกิน ฿350", hint: "มื้อทั่วไป" },
  { value: 500, label: "ไม่เกิน ฿500", hint: "จัดเต็ม" },
  { value: 600, label: "฿600 ขึ้นไป", hint: "เปิดกว้าง" },
];
